spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/comex?createDatabaseIfNotExist=true
    username: root
    password:

  redis:
    host: localhost
    port: 6379
  cache:
    redis:
      time-to-live: 60000

management:
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: @project.name@
    version: @project.version@

api:
  jwt:
    expiracao: 86400000
    secret: DF[NN]#*(;Nge'N#.g5juDl,tNy/f5j#yjNL5Kj7yNQKDyft7N23#Q4L(*(U
